# NumPy

## Ho creato un array NumPy da una lista

In [1]:
import numpy as np
list = [1,2,6]

array1 = np.array(list)
print(array1)

[1 2 6]


### Ho fatto una matrice 

In [2]:
lista2 = [7,1,2]

array2 = np.array([list, lista2])
array2 = np.array([[2,3,4],[1,1,1]])

print(array2)

[[2 3 4]
 [1 1 1]]


#### Ndim mi dice la dimensione dell'array

In [3]:
array2.ndim

2

#### Shape mi dice la forma dell'array

In [4]:
array2.shape

(2, 3)

#### Size mi dice il numero di elementi dell'array

In [5]:
array2.size

6

#### Ho Creato una matrice, con 3 array, ognuna da 4 elementi ogni elemento è 8

In [6]:
array_8 = np.ones((3,4))*8
print(array_8)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
